CATEGORIES_SET = (
    'Kunst',
    # 'Antiques & Collectibles',
    'Architektur',
    'Psychologie',
    'Philosophie',
    'Abenteuer',
    'Romantik',
    'Biografie & Autobiografie',
    'Körper, Geist & Seele',
    'Betriebswirtschaftslehre',
    'Computers',
    'Handwerk & Hobbys',
    'Design',
    'Drama',
    'Bildung',
    'Fremdsprachenstudium',
    'Gartenarbeit',
    'Eigenheim',
    'Sprachkünste und Disziplinen',
    'Jura',
    'Mathematik',
    'Haustiere',
    'Fotografie',
    'Religion',
    'Wissenschaft',
    'Fiktion',
    'Sachbücher',
    'Reisen',
    # 'Echte Kriminalität',
    'Spiele & Aktivitäten'
    'Humor',
    'Jugendliteratur',
    'Jugendliteratur (Sachbücher)',
    'Medizin',
    'Kochen',
    'Selbsthilfe',
    'Musik',
    'Gesundheit & Fitness',
    'Geschichte',
    'Natur',
    # 'Performing Arts',
    'Poesie',
    'Familie & Beziehungen',
    'Politikwissenschaft',
    'Sozialwissenschaften',
    'Sport',
    'Technologie',
    'Unbekannt',
)

CATEGORIES_SET_SLUG = (
    'kunst',
    # 'antiques-collectibles',
    'architektur',
    'abenteur',
    'biografie-autobiografie',
    'koerper-geist-seele',
    'betriebswirtschaftslehre',
    'kochen',
    'computers',
    'handwerk-hobbys',
    'design',
    'drama',
    'bildung',
    'familie-beziehungen',
    'fiktion',
    'fremdsprachenstudium',
    'spiele-aktivitaeten',
    'gartenarbeit',
    'gesundheit-fitness',
    'geschichte',
    'eigenheim',
    'humor',
    'jugendliteratu',
    'jugendliteratur-sachbuecher',
    'sprachkünste-disziplinen',
    'jura',
    'mathematik',
    'medizin',
    'musik',
    'natur',
    'sachbuecher',
    # 'performing-arts',
    'haustiere',
    'fotografie',
    'philosophie',
    'poesie',
    'politikwissenschaft',
    'psychologie',
    'religion',
    'romantik',
    'wissenschaft',
    'selbshilfe',
    'sozialwissenschaften',
    'sport',
    'technologie',
    'reisen',
    # 'true-crime',
    'unbekannt',
)



# FROM MODELS

CATEGORIES = (
    ('fantasy', 'Fantasy'),
    ('psychology', 'Psychology'),
    ('philosophy', 'Philosophy'),
    ('adventure', 'Adventure'),
    ('romance', 'Romance'),
    ('biographies-memoirs', 'Biographies & Memoirs'),
    ('mystery', 'Mystery'),
    ('horror', 'Horror'),
    ('thriller', 'Thriller'),
    ('paranormal', 'Paranormal'),
    ('historical-fiction', 'Historical fiction'),
    ('science-fiction', 'Science Fiction'),
    ('memoir', 'Memoir'),
    ('cooking', 'Cooking'),
    ('art', 'Art'),
    ('self-help', 'Self-help'),
    ('education-teaching', 'Education & Teaching'),
    ('health', 'Health'),
    ('history', 'History'),
    ('travel', 'Travel'),
    ('guide-how-to', 'Guide, How-to'),
    ('families-relationships', 'Families & Relationships'),
    ('humor', 'Humor'),
    ('children', 'Children'),
    ('unknown', 'Unknown')
)

NEW_CATEGORIES = (
    ('art', 'Art'),
    ('antiques-collectibles', 'Antiques & Collectibles'),
    ('architecture', 'Architecture'),
    ('psychology', 'Psychology'),
    ('philosophy', 'Philosophy'),
    ('adventure', 'Adventure'),
    ('romance', 'Romance'),
    ('biography-autobiography', 'Biography & Autobiography'),
    ('body-mind-spirit', 'Body, Mind & Spirit'),
    ('business-economics', 'Business & Economics'),
    ('computers', 'Computers'),
    ('crafts-hobbies', 'Crafts & Hobbies'),
    ('design', 'Design'),
    ('drama', 'Drama'),
    ('education', 'Education'),
    ('foreign-language-study', 'Foreign Language Study'),
    ('gardening', 'Gardening'),
    ('house-home', 'House & Home'),
    ('language-arts-disciplines', 'Language Arts & Disciplines'),
    ('law', 'Law'),
    ('mathematic', 'Mathematic'),
    ('pets', 'Pets'),
    ('photography', 'Photography'),
    ('religion', 'Religion'),
    ('science', 'Science'),
    ('fiction', 'Fiction'),
    ('non-fiction', 'Non-Fiction'),
    ('travel', 'Travel'),
    ('true-crime', 'True Crime'),
    ('games-activities', 'Games & Activities'),
    ('humor', 'Humor'),
    ('juvenile-fiction', 'Juvenile Fiction'),
    ('juvenile-nonfiction', 'Juvenile Nonfiction'),
    ('medical', 'Medical'),
    ('cooking', 'Cooking'),
    ('self-help', 'Self-help'),
    ('music', 'Music'),
    ('health-fitness', 'Health & Fitness'),
    ('history', 'History'),
    ('nature', 'Nature'),
    ('performing-arts', 'Performing Arts'),
    ('poetry', 'Poetry'),
    ('family-relationships', 'Family & Relationships'),
    ('political-science', 'Political Science'),
    ('social-science', 'Social Science'),
    ('sports-recreation', 'Sports & Recreation'),
    ('technology', 'Technology'),
    ('unknown', 'Unknown'),
)


# from views

CATEGORIES_SET = (
    'Biographien',
    'Comics / Mangas',
    'Fachbücher',
    'Fantasy / Science Fiction',
    'Fitness / Gesundheit',
    'Freizeit / Hobby',
    'Geschichte',
    'Humor / Unterhaltung',
    'Klassiker der Literatur',
    'Krimis / Thriller',
    'Liebe / Romantik',
    'Lyrik / Gedichte',
    'Reiseführer / Reiseliteratur',
    'Romane / Erzählungen',
    'Sachbücher',
    'Sport',
    'Unbekannt',
)

CATEGORIES_SET_SLUG = (
    'biographien',
    'comics-mangas',
    'fachbuecher',
    'fantasy-science-fiction',
    'fitness-gesundheit',
    'freizeit-hobby',
    'geschichte',
    'humor-unterhaltung',
    'klassiker-der-literatur',
    'krimis-thriller',
    'liebe-romantik',
    'lyrik-gedichte',
    'reisefuehrer-reiseliteratur',
    'romane-erzaehlungen',
    'sachbuecher',
    'sport',
    'unbekannt',
)